if('scrollRestoration'in history)history.scrollRestoration='manual';const navigationEntry=performance.getEntriesByType('navigation')[0];if(navigationEntry?.type==='reload'&&window.location.hash)history.replaceState(null,'',window.location.pathname+window.location.search);window.addEventListener('load',()=>{if(navigationEntry?.type==='reload')window.scrollTo(0,0)});

import PhotoSwipeLightbox from 'https://unpkg.com/photoswipe@5.4.4/dist/photoswipe-lightbox.esm.js';
let allPhotos=[],currentFilter='all',visiblePhotos=[];
const categoryOrder=['portraits','street','urban','landscapes','travel','furry-friends'];
const featuredDescriptions={portraits:'Faces, expressions, and the moments in between.',street:'Everyday moments, captured as they unfold.',urban:'City life, architecture, and the rhythm of the streets.',landscapes:'Quiet places, open skies, and moments worth stopping for.',travel:'New places, new perspectives, and memories along the way.','furry-friends':'The little personalities that make every moment better.'};
const photoSwipe=new PhotoSwipeLightbox({dataSource:[],bgOpacity:.94,showHideAnimationType:'fade',showAnimationDuration:333,hideAnimationDuration:333,easing:'cubic-bezier(.4,0,.22,1)',initialZoomLevel:'fit',secondaryZoomLevel:1,preload:[1,2],escKey:true,arrowKeys:true,trapFocus:true,returnFocus:true,mainClass:'zen-pswp',pswpModule:()=>import('https://unpkg.com/photoswipe@5.4.4/dist/photoswipe.esm.js')});
photoSwipe.on('uiRegister',()=>{photoSwipe.pswp.ui.registerElement({name:'custom-caption',order:9,isButton:false,appendTo:'root',html:'',onInit:(el,pswp)=>{pswp.on('change',()=>{const photo=visiblePhotos[pswp.currIndex];if(photo)el.innerHTML=`<strong>${escapeHtml(photo.title)}</strong><span>${escapeHtml(formatCategory(photo.category))}</span>`})}})});photoSwipe.init();
function escapeHtml(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;')}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function formatCategory(c){return c.split('-').map(w=>w.charAt(0).toUpperCase()+w.slice(1)).join(' ')}
function updateFeatured(){const cats=[...new Set(allPhotos.map(p=>p.category))];if(!cats.length)return;const category=cats[Math.floor(Math.random()*cats.length)],photos=allPhotos.filter(p=>p.category===category),photo=photos[Math.floor(Math.random()*photos.length)];document.getElementById('featuredTitle').textContent=formatCategory(category);document.getElementById('featuredDescription').textContent=featuredDescriptions[category]||'A collection of moments from the gallery.';const button=document.getElementById('featuredButton');button.textContent=`Explore ${formatCategory(category)} →`;button.href='#gallery';document.querySelector('.hero').style.setProperty('--hero-bg',`url(\"${photo.path}\")`);const box=document.getElementById('heroPhotoWrap');box.innerHTML='';const img=document.createElement('img');img.className='hero-photo';img.src=photo.path;img.alt=`${formatCategory(category)} featured photo`;img.loading='eager';box.appendChild(img)}
function createFilters(){const filters=document.getElementById('filters');filters.innerHTML='';const available=new Set(allPhotos.map(p=>p.category)),categories=[...categoryOrder.filter(c=>available.has(c)),...[...available].filter(c=>!categoryOrder.includes(c)).sort()];const all=document.createElement('button');all.textContent='All';all.className='active';all.onclick=()=>filterPhotos('all',all);filters.appendChild(all);categories.forEach(c=>{const b=document.createElement('button');b.textContent=formatCategory(c);b.onclick=()=>filterPhotos(c,b);filters.appendChild(b)});document.getElementById('categoryCount').textContent=categories.length}
async function loadPhotos(){try{const r=await fetch('photos.json');if(!r.ok)throw new Error('Could not load photos.json');const d=await r.json();allPhotos=shuffle([...d.photos]);createFilters();updateFeatured();updatePhotoCount();displayPhotos(currentFilter)}catch(e){console.error('Error loading photos:',e)}}
function updatePhotoCount(){document.getElementById('photoCount').textContent=currentFilter==='all'?allPhotos.length:allPhotos.filter(p=>p.category===currentFilter).length}
function displayPhotos(category){const grid=document.getElementById('photoGrid');grid.innerHTML='';visiblePhotos=category==='all'?allPhotos:allPhotos.filter(p=>p.category===category);visiblePhotos.forEach((photo,index)=>{const d=document.createElement('div');d.className='photo';d.onclick=()=>openPhoto(index);const img=document.createElement('img');img.src=photo.path;img.alt=photo.title;img.loading='lazy';d.appendChild(img);grid.appendChild(d)})}
function filterPhotos(category,button){currentFilter=category;document.querySelectorAll('.filters button').forEach(b=>b.classList.remove('active'));if(button)button.classList.add('active');updatePhotoCount();displayPhotos(category)}
function openPhoto(index){if(!visiblePhotos.length)return;photoSwipe.loadAndOpen(index,visiblePhotos.map(p=>({src:p.path,width:Number(p.width),height:Number(p.height),alt:p.title})))}
document.addEventListener('DOMContentLoaded',loadPhotos);